/*
# Seed Initial Data: Categories and Products

## Overview
Populates the database with the 9 existing categories and 26 products
that were previously hardcoded in the frontend. This ensures the store
has identical content when switching to database-driven data.

## Data
- 9 categories (tshirts, shirts, hoodies, jeans, dresses, sneakers, bags, watches, accessories)
- 26 products with bilingual names/descriptions, prices, images, colors, sizes, tags

## Notes
- Uses ON CONFLICT to be idempotent (safe to re-run)
- Product IDs match the original hardcoded IDs for cart/wishlist localStorage compatibility
- Colors stored as jsonb array of {name, hex} objects
*/

-- ============================================================
-- CATEGORIES
-- ============================================================
INSERT INTO categories (key, name_ar, name_en, sort_order) VALUES
  ('tshirts', 'تيشيرتات', 'T-Shirts', 1),
  ('shirts', 'قمصان', 'Shirts', 2),
  ('hoodies', 'هوديز', 'Hoodies', 3),
  ('jeans', 'جينز', 'Jeans', 4),
  ('dresses', 'فساتين', 'Dresses', 5),
  ('sneakers', 'أحذية', 'Shoes', 6),
  ('bags', 'حقائب', 'Bags', 7),
  ('watches', 'ساعات', 'Watches', 8),
  ('accessories', 'إكسسوار', 'Accessories', 9)
ON CONFLICT (key) DO NOTHING;

-- ============================================================
-- PRODUCTS (26 items)
-- ============================================================
INSERT INTO products (id, name_ar, name_en, category_key, gender, price, old_price, image, gallery, description_ar, description_en, colors, sizes, rating, reviews, tags, occasion, is_new, is_trending, popularity, is_active, stock) VALUES
(1, 'تيشيرت أسود كلاسيك', 'Classic Black T-Shirt', 'tshirts', 'men', 120, 160, 'https://images.pexels.com/photos/11158639/pexels-photo-11158639.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', ARRAY['https://images.pexels.com/photos/11158639/pexels-photo-11158639.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/13651809/pexels-photo-13651809.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'], 'تيشيرت قطني أسود بقصّة عصرية مريحة، مثالي للإطلالات اليومية والكاجوال.', 'Cotton black t-shirt with a modern comfortable fit, perfect for everyday casual looks.', '[{"name":"black","hex":"#1a1a1a"},{"name":"white","hex":"#f7f5f2"},{"name":"navy","hex":"#1f2a44"}]'::jsonb, ARRAY['S','M','L','XL'], 4.6, 128, ARRAY['cotton','basic','everyday','minimal'], ARRAY['casual','summer'], true, true, 95, true, 100),
(2, 'تيشيرت أزرق رياضي', 'Sport Blue T-Shirt', 'tshirts', 'men', 135, NULL, 'https://images.pexels.com/photos/13651809/pexels-photo-13651809.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', ARRAY['https://images.pexels.com/photos/13651809/pexels-photo-13651809.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'], 'تيشيرت أزرق داكن بخامة مرنة تمنحك راحة طوال اليوم مع لمسة رياضية أنيقة.', 'Dark blue t-shirt with stretchy fabric for all-day comfort and a sporty elegant touch.', '[{"name":"blue","hex":"#3b6db5"},{"name":"black","hex":"#1a1a1a"},{"name":"gray","hex":"#8a8a8a"}]'::jsonb, ARRAY['S','M','L','XL'], 4.4, 86, ARRAY['sport','stretch','everyday'], ARRAY['casual','sport','summer'], false, true, 78, true, 80),
(3, 'قميص زهري كاجوال', 'Floral Casual Shirt', 'shirts', 'men', 210, NULL, 'https://images.pexels.com/photos/2421356/pexels-photo-2421356.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', ARRAY['https://images.pexels.com/photos/2421356/pexels-photo-2421356.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'], 'قميص بنقشة زهرية استوائية خفيف مثالي للنزهات الصيفية وإطلالات الإجازات.', 'Light tropical floral shirt, perfect for summer outings and vacation looks.', '[{"name":"green","hex":"#3d7a55"},{"name":"white","hex":"#f7f5f2"},{"name":"blue","hex":"#3b6db5"}]'::jsonb, ARRAY['S','M','L','XL'], 4.7, 54, ARRAY['floral','summer','vacation','lightweight'], ARRAY['casual','summer','party'], true, false, 81, true, 60),
(4, 'قميص أزرق أنيق', 'Elegant Blue Shirt', 'shirts', 'men', 240, NULL, 'https://images.pexels.com/photos/19852754/pexels-photo-19852754.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', ARRAY['https://images.pexels.com/photos/19852754/pexels-photo-19852754.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'], 'قميص أزرق بقصّة حديثة يناسب الإطلالات شبه الرسمية والخروجات المسائية.', 'Modern-cut blue shirt suited for smart-casual and evening outings.', '[{"name":"blue","hex":"#3b6db5"},{"name":"navy","hex":"#1f2a44"},{"name":"white","hex":"#f7f5f2"}]'::jsonb, ARRAY['S','M','L','XL','XXL'], 4.5, 72, ARRAY['smart','evening','slim-fit'], ARRAY['business','formal','evening'], false, false, 70, true, 50),
(5, 'هودي أسود ستريت وير', 'Black Streetwear Hoodie', 'hoodies', 'unisex', 280, 340, 'https://images.pexels.com/photos/15127546/pexels-photo-15127546.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', ARRAY['https://images.pexels.com/photos/15127546/pexels-photo-15127546.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/28701960/pexels-photo-28701960.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'], 'هودي بقماش سميك دافئ بتصميم ستريت وير عصري يمنحك إطلالة جريئة ومريحة.', 'Thick warm hoodie with a modern streetwear design for a bold, comfortable look.', '[{"name":"black","hex":"#1a1a1a"},{"name":"gray","hex":"#8a8a8a"},{"name":"navy","hex":"#1f2a44"}]'::jsonb, ARRAY['S','M','L','XL','XXL'], 4.8, 210, ARRAY['streetwear','warm','oversized','winter'], ARRAY['casual','winter'], false, true, 98, true, 120),
(6, 'هودي رمادي رياضي', 'Sporty Gray Hoodie', 'hoodies', 'men', 260, NULL, 'https://images.pexels.com/photos/28701960/pexels-photo-28701960.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', ARRAY['https://images.pexels.com/photos/28701960/pexels-photo-28701960.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'], 'هودي رمادي خفيف بخامة قطنية ناعمة مثالي للجلسات الرياضية والكاجوال.', 'Light gray hoodie with soft cotton fabric, ideal for sports and casual sessions.', '[{"name":"gray","hex":"#8a8a8a"},{"name":"black","hex":"#1a1a1a"},{"name":"beige","hex":"#d8c4a0"}]'::jsonb, ARRAY['S','M','L','XL'], 4.5, 96, ARRAY['sport','lightweight','cotton'], ARRAY['casual','sport','winter'], false, false, 74, true, 70),
(7, 'جينز أزرق ضيق', 'Slim Blue Jeans', 'jeans', 'men', 320, NULL, 'https://images.pexels.com/photos/16069736/pexels-photo-16069736.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', ARRAY['https://images.pexels.com/photos/16069736/pexels-photo-16069736.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'], 'جينز أزرق بقصّة ضيقة عصرية وخامة دينيم مرنة تمنحك حرية الحركة.', 'Blue jeans with a modern slim cut and stretch denim for freedom of movement.', '[{"name":"blue","hex":"#3b6db5"},{"name":"navy","hex":"#1f2a44"},{"name":"black","hex":"#1a1a1a"}]'::jsonb, ARRAY['28','30','32','34','36'], 4.6, 143, ARRAY['denim','slim','stretch','everyday'], ARRAY['casual','business','evening'], true, false, 88, true, 90),
(8, 'جاكيت دينيم كلاسيك', 'Classic Denim Jacket', 'jeans', 'men', 380, NULL, 'https://images.pexels.com/photos/2229712/pexels-photo-2229712.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', ARRAY['https://images.pexels.com/photos/2229712/pexels-photo-2229712.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'], 'جاكيت دينيم كلاسيكي بتصميم خالد يناسب جميع المواسم ويكمل أي إطلالة.', 'Classic denim jacket with a timeless design that suits all seasons and completes any look.', '[{"name":"blue","hex":"#3b6db5"},{"name":"navy","hex":"#1f2a44"}]'::jsonb, ARRAY['S','M','L','XL'], 4.7, 67, ARRAY['denim','jacket','layering','classic'], ARRAY['casual','winter'], false, true, 82, true, 40),
(9, 'فستان أسود سهرة', 'Black Evening Dress', 'dresses', 'women', 520, 650, 'https://images.pexels.com/photos/14801160/pexels-photo-14801160.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', ARRAY['https://images.pexels.com/photos/14801160/pexels-photo-14801160.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'], 'فستان أسود لامع بتصميم أنيق للسهرة يمنحك إطلالة جذابة وفاخرة.', 'Glowing black evening dress with an elegant design for a captivating, luxurious look.', '[{"name":"black","hex":"#1a1a1a"},{"name":"red","hex":"#b44545"},{"name":"navy","hex":"#1f2a44"}]'::jsonb, ARRAY['XS','S','M','L'], 4.9, 187, ARRAY['evening','elegant','glam','party'], ARRAY['party','evening','formal'], false, true, 99, true, 30),
(10, 'فستان أزرق صيفي', 'Summer Blue Dress', 'dresses', 'women', 340, NULL, 'https://images.pexels.com/photos/37015070/pexels-photo-37015070.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', ARRAY['https://images.pexels.com/photos/37015070/pexels-photo-37015070.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'], 'فستان أزرق زاهي بقصّة انسيابية مريحة مثالي لأيام الصيف والمناسبات النهارية.', 'Bright blue dress with a flowing comfortable cut, perfect for summer days and daytime events.', '[{"name":"blue","hex":"#3b6db5"},{"name":"pink","hex":"#e3a9b6"},{"name":"white","hex":"#f7f5f2"}]'::jsonb, ARRAY['XS','S','M','L'], 4.7, 92, ARRAY['summer','flowy','bright','daytime'], ARRAY['casual','summer','party'], true, false, 86, true, 55),
(11, 'فستان أبيض أنيق', 'Elegant White Dress', 'dresses', 'women', 410, NULL, 'https://images.pexels.com/photos/20483777/pexels-photo-20483777.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', ARRAY['https://images.pexels.com/photos/20483777/pexels-photo-20483777.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'], 'فستان أبيض بتصميم راقٍ يبعث على البساطة والأناقة، يناسب المناسبات الخاصة.', 'White dress with a refined design that radiates simplicity and elegance for special occasions.', '[{"name":"white","hex":"#f7f5f2"},{"name":"beige","hex":"#d8c4a0"},{"name":"pink","hex":"#e3a9b6"}]'::jsonb, ARRAY['XS','S','M','L'], 4.8, 64, ARRAY['elegant','minimal','special'], ARRAY['formal','evening','party'], false, false, 79, true, 25),
(12, 'بلوزة بيضاء كاجوال', 'Casual White Blouse', 'shirts', 'women', 190, NULL, 'https://images.pexels.com/photos/29090990/pexels-photo-29090990.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', ARRAY['https://images.pexels.com/photos/29090990/pexels-photo-29090990.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'], 'بلوزة بيضاء بقصّة عصرية وخامة ناعمة تناسب إطلالات العمل والكاجوال.', 'White blouse with a modern cut and soft fabric suited for work and casual looks.', '[{"name":"white","hex":"#f7f5f2"},{"name":"beige","hex":"#d8c4a0"},{"name":"pink","hex":"#e3a9b6"}]'::jsonb, ARRAY['XS','S','M','L'], 4.5, 48, ARRAY['work','soft','everyday'], ARRAY['business','casual'], false, false, 68, true, 65),
(13, 'إطلالة بيج عصرية', 'Modern Beige Ensemble', 'dresses', 'women', 360, NULL, 'https://images.pexels.com/photos/10324419/pexels-photo-10324419.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', ARRAY['https://images.pexels.com/photos/10324419/pexels-photo-10324419.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'], 'إطلالة بيج عصرية ببنطال عالي الخصر وبلوزة زرقاء، تصميم أنيق ومريح.', 'Modern beige ensemble with high-waist pants and blue top, an elegant and comfortable design.', '[{"name":"beige","hex":"#d8c4a0"},{"name":"blue","hex":"#3b6db5"},{"name":"white","hex":"#f7f5f2"}]'::jsonb, ARRAY['XS','S','M','L'], 4.6, 39, ARRAY['modern','high-waist','chic'], ARRAY['business','casual','evening'], true, false, 72, true, 35),
(14, 'إطلالة ستوديو أنيقة', 'Studio Elegant Look', 'dresses', 'women', 300, NULL, 'https://images.pexels.com/photos/9263790/pexels-photo-9263790.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', ARRAY['https://images.pexels.com/photos/9263790/pexels-photo-9263790.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'], 'إطلالة أنيقة بإطلالة كاجوال راقية تناسب الجلسات اليومية والصور الاحترافية.', 'Elegant look with a smart-casual vibe suited for everyday outings and professional photos.', '[{"name":"white","hex":"#f7f5f2"},{"name":"beige","hex":"#d8c4a0"},{"name":"black","hex":"#1a1a1a"}]'::jsonb, ARRAY['XS','S','M','L'], 4.4, 27, ARRAY['chic','studio','minimal'], ARRAY['casual','business'], false, false, 61, true, 20),
(15, 'سنيكرز أبيض كلاسيك', 'Classic White Sneakers', 'sneakers', 'unisex', 450, 560, 'https://images.pexels.com/photos/12628400/pexels-photo-12628400.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', ARRAY['https://images.pexels.com/photos/12628400/pexels-photo-12628400.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'], 'حذاء رياضي أبيض بتصميم كلاسيكي نظيف يناسب جميع الإطلالات الكاجوال.', 'White sneakers with a clean classic design that suits all casual looks.', '[{"name":"white","hex":"#f7f5f2"},{"name":"black","hex":"#1a1a1a"},{"name":"silver","hex":"#c7c9cf"}]'::jsonb, ARRAY['38','39','40','41','42','43','44'], 4.8, 256, ARRAY['sneakers','white','classic','everyday'], ARRAY['casual','sport','summer'], false, true, 97, true, 80),
(16, 'سنيكرز أسود ورياضية', 'Black Sport Sneakers', 'sneakers', 'men', 480, NULL, 'https://images.pexels.com/photos/19271383/pexels-photo-19271383.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', ARRAY['https://images.pexels.com/photos/19271383/pexels-photo-19271383.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'], 'سنيكرز أسود بلمسات حمراء وخامة متينة، مثالي للرياضة والإطلالات اليومية.', 'Black sneakers with red accents and durable fabric, ideal for sports and daily looks.', '[{"name":"black","hex":"#1a1a1a"},{"name":"red","hex":"#b44545"},{"name":"white","hex":"#f7f5f2"}]'::jsonb, ARRAY['40','41','42','43','44','45'], 4.6, 134, ARRAY['sport','durable','black'], ARRAY['sport','casual'], false, false, 84, true, 60),
(17, 'سنيكرز أزرق مميز', 'Blue Statement Sneakers', 'sneakers', 'unisex', 430, NULL, 'https://images.pexels.com/photos/13580587/pexels-photo-13580587.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', ARRAY['https://images.pexels.com/photos/13580587/pexels-photo-13580587.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'], 'سنيكرز أزرق بتصميم جريء يضيف لمسة عصرية لأي إطلالة كاجوال.', 'Blue sneakers with a bold design that adds a modern touch to any casual look.', '[{"name":"blue","hex":"#3b6db5"},{"name":"white","hex":"#f7f5f2"}]'::jsonb, ARRAY['38','39','40','41','42','43'], 4.5, 71, ARRAY['sneakers','blue','statement'], ARRAY['casual','sport','summer'], true, false, 76, true, 45),
(18, 'حقيبة جلد فاخرة', 'Premium Leather Handbag', 'bags', 'women', 560, 700, 'https://images.pexels.com/photos/7953286/pexels-photo-7953286.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', ARRAY['https://images.pexels.com/photos/7953286/pexels-photo-7953286.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'], 'حقيبة جلدية فاخرة بتصميم هندسي أنيق تضيف لمسة فخامة لإطلالتك.', 'Premium leather handbag with an elegant geometric design that adds luxury to your look.', '[{"name":"brown","hex":"#6b4a2b"},{"name":"black","hex":"#1a1a1a"},{"name":"beige","hex":"#d8c4a0"}]'::jsonb, ARRAY['One Size'], 4.9, 158, ARRAY['leather','premium','elegant','bag'], ARRAY['formal','business','evening'], false, true, 92, true, 25),
(19, 'حقيبة خضراء عصرية', 'Modern Green Handbag', 'bags', 'women', 420, NULL, 'https://images.pexels.com/photos/22432991/pexels-photo-22432991.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', ARRAY['https://images.pexels.com/photos/22432991/pexels-photo-22432991.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'], 'حقيبة بلون أخضر وبيج بتصميم عصري يناسب الإطلالات اليومية والمناسبات.', 'Green and beige handbag with a modern design for daily looks and occasions.', '[{"name":"green","hex":"#3d7a55"},{"name":"beige","hex":"#d8c4a0"}]'::jsonb, ARRAY['One Size'], 4.6, 44, ARRAY['modern','bag','everyday'], ARRAY['casual','business'], true, false, 69, true, 30),
(20, 'حقيبة بنية كلاسيك', 'Classic Brown Handbag', 'bags', 'women', 480, NULL, 'https://images.pexels.com/photos/35666033/pexels-photo-35666033.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', ARRAY['https://images.pexels.com/photos/35666033/pexels-photo-35666033.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'], 'حقيبة بنية بتصميم كلاسيكي خالد من الجلد الطبيعي تكتمل بألوان دافئة.', 'Brown handbag with a timeless classic design in genuine leather and warm tones.', '[{"name":"brown","hex":"#6b4a2b"},{"name":"beige","hex":"#d8c4a0"},{"name":"black","hex":"#1a1a1a"}]'::jsonb, ARRAY['One Size'], 4.7, 58, ARRAY['leather','classic','bag'], ARRAY['business','casual','formal'], false, false, 73, true, 20),
(21, 'ساعة جلد سوداء', 'Black Leather Watch', 'watches', 'men', 680, 820, 'https://images.pexels.com/photos/22032446/pexels-photo-22032446.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', ARRAY['https://images.pexels.com/photos/22032446/pexels-photo-22032446.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'], 'ساعة يد جلدية سوداء بتصميم مينيمالي أنيق تضيف لمسة فخامة هادئة.', 'Black leather wristwatch with a minimal elegant design that adds quiet luxury.', '[{"name":"black","hex":"#1a1a1a"},{"name":"brown","hex":"#6b4a2b"}]'::jsonb, ARRAY['One Size'], 4.9, 176, ARRAY['watch','leather','minimal','luxury'], ARRAY['formal','business','evening'], false, true, 94, true, 15),
(22, 'ساعة بميناء أزرق', 'Blue Dial Watch', 'watches', 'men', 750, NULL, 'https://images.pexels.com/photos/3766111/pexels-photo-3766111.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', ARRAY['https://images.pexels.com/photos/3766111/pexels-photo-3766111.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'], 'ساعة بميناء أزرق ياقاني وسوار معدني شبكي، تصميم راقٍ للمناسبات الرسمية.', 'Sapphire blue dial watch with metal mesh strap, a refined design for formal occasions.', '[{"name":"silver","hex":"#c7c9cf"},{"name":"blue","hex":"#3b6db5"},{"name":"gold","hex":"#c8a96a"}]'::jsonb, ARRAY['One Size'], 4.8, 89, ARRAY['watch','silver','formal','luxury'], ARRAY['formal','business','evening'], true, false, 85, true, 10),
(23, 'ساعة هيكل عظمي', 'Skeleton Dial Watch', 'watches', 'unisex', 890, NULL, 'https://images.pexels.com/photos/7627873/pexels-photo-7627873.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', ARRAY['https://images.pexels.com/photos/7627873/pexels-photo-7627873.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'], 'ساعة بتصميم هيكل عظمي وأرقام رومانية، قطعة فنية فاخرة لعشاق التفاصيل.', 'Skeleton dial watch with Roman numerals, a luxurious art piece for detail lovers.', '[{"name":"gold","hex":"#c8a96a"},{"name":"silver","hex":"#c7c9cf"},{"name":"black","hex":"#1a1a1a"}]'::jsonb, ARRAY['One Size'], 4.7, 41, ARRAY['watch','luxury','skeleton','unique'], ARRAY['formal','evening'], false, false, 77, true, 8),
(24, 'نظارة شمسية عصرية', 'Modern Sunglasses', 'accessories', 'unisex', 180, NULL, 'https://images.pexels.com/photos/29332844/pexels-photo-29332844.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', ARRAY['https://images.pexels.com/photos/29332844/pexels-photo-29332844.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'], 'نظارة شمسية عصرية مع علبة جلدية أنيقة، حماية وأناقة في آنٍ واحد.', 'Modern sunglasses with an elegant leather case, protection and style in one.', '[{"name":"black","hex":"#1a1a1a"},{"name":"brown","hex":"#6b4a2b"},{"name":"gold","hex":"#c8a96a"}]'::jsonb, ARRAY['One Size'], 4.5, 63, ARRAY['sunglasses','summer','accessory'], ARRAY['casual','summer'], true, false, 80, true, 50),
(25, 'بوت جلد أسود عالي', 'Black Knee-High Leather Boots', 'sneakers', 'women', 620, 780, 'https://images.pexels.com/photos/27598915/pexels-photo-27598915.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', ARRAY['https://images.pexels.com/photos/27598915/pexels-photo-27598915.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'], 'بوت جلد أسود طويل للركبة بتصميم أنيق يضيف لمسة فاخرة لإطلالات الشتاء.', 'Black knee-high leather boots with an elegant design that adds luxury to winter looks.', '[{"name":"black","hex":"#1a1a1a"},{"name":"brown","hex":"#6b4a2b"}]'::jsonb, ARRAY['36','37','38','39','40','41'], 4.8, 112, ARRAY['boots','leather','winter','elegant'], ARRAY['winter','evening','formal'], false, true, 90, true, 20),
(26, 'بوت بيج كلاسيك', 'Classic Beige Boots', 'sneakers', 'women', 540, NULL, 'https://images.pexels.com/photos/27639594/pexels-photo-27639594.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', ARRAY['https://images.pexels.com/photos/27639594/pexels-photo-27639594.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'], 'بوت بيج بتصميم كلاسيكي ورباط حديث، خامة جلد ناعم لإطلالة شتوية أنيقة.', 'Beige boots with a classic design and modern lacing, soft leather for an elegant winter look.', '[{"name":"beige","hex":"#d8c4a0"},{"name":"brown","hex":"#6b4a2b"}]'::jsonb, ARRAY['36','37','38','39','40'], 4.6, 47, ARRAY['boots','beige','winter'], ARRAY['winter','casual'], false, false, 66, true, 15)
ON CONFLICT (id) DO NOTHING;

-- Sync the serial sequence so new products get the next available id
SELECT setval('products_id_seq', (SELECT MAX(id) FROM products));